name: silent_cache
description: "A minimalist, secure note-taking application built with Flutter, inspired by Obsidian's dark theme and functionality."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.4
  shared_preferences: ^2.5.3
  timeago: ^3.7.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
